name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  install:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [11, 17]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 50

    - name: Setup local maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-cache-${{ hashFiles('**/pom.xml') }}

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}

    - name: Build with Maven
      run: ./mvnw --errors --no-transfer-progress install

    - name: Difference Check
      run: ./.ci/validation.sh git-diff
